/** Audit log — immutable record of who-did-what-when, for compliance & forensics. */
import { db } from "@/lib/db";
import { requestContext } from "./context";
import { uuid } from "@eks/common";

export interface AuditEvent {
  readonly action: string;
  readonly entityType: string;
  readonly entityId?: string;
  readonly organizationId: string;
  readonly actorUserId?: string | null;
  readonly metadata?: Record<string, unknown>;
  readonly ipAddress?: string;
}

class AuditLogImpl {
  async record(event: AuditEvent): Promise<void> {
    const ctx = requestContext();
    try {
      await db.auditLog.create({
        data: {
          id: undefined, // generated by DB
          organizationId: event.organizationId,
          actorUserId: event.actorUserId ?? ctx?.actorUserId ?? null,
          action: event.action,
          entityType: event.entityType,
          entityId: event.entityId ?? null,
          metadata: JSON.stringify(event.metadata ?? {}),
          ipAddress: event.ipAddress ?? null,
        },
      });
    } catch {
      // Audit failures must never crash the request. In production, push to a
      // fallback queue / outbox for later write. Here we swallow + log.
      console.error("[audit] failed to record", event.action);
    }
  }
}

export const AuditLog = AuditLogImpl;
export type { AuditEvent as AuditEventType };
export const audit = new AuditLogImpl();

/** Stable audit action codes — use these, never string literals. */
export const AuditActions = {
  BOOKING_CREATED: "BOOKING_CREATED",
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
  PAYMENT_INITIATED: "PAYMENT_INITIATED",
  PAYMENT_SUCCEEDED: "PAYMENT_SUCCEEDED",
  PAYOUT_REQUESTED: "PAYOUT_REQUESTED",
  FEATURE_FLAG_TOGGLED: "FEATURE_FLAG_TOGGLED",
  SERVICE_CREATED: "SERVICE_CREATED",
  CONFIG_CHANGED: "CONFIG_CHANGED",
  AUTH_LOGIN: "AUTH_LOGIN",
  AUTH_LOGOUT: "AUTH_LOGOUT",
} as const;

export { uuid };
