/** Connector-specific error codes. */
export const CONN_ERRORS = {
  AUTH_FAILED: "CONN_AUTH_FAILED",
  RATE_LIMITED: "CONN_RATE_LIMITED",
  TIMEOUT: "CONN_TIMEOUT",
  CIRCUIT_OPEN: "CONN_CIRCUIT_OPEN",
  SYNC_CONFLICT: "CONN_SYNC_CONFLICT",
  SCHEMA_MISMATCH: "CONN_SCHEMA_MISMATCH",
  HEALTH_CHECK_FAILED: "CONN_HEALTH_CHECK_FAILED",
} as const;
